# @format

name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^3.2.1
  flutter_slidable:
  expandable: ^5.0.1
  visibility_detector: ^0.2.2
  url_launcher:
  http:
  string_similarity: ^2.0.0
  intl:
  html: ^0.15.0
  share: ^2.0.4
  flutter_html: ^2.1.5
  flutter_inappwebview: ^5.6.0+2
  flutter_screenutil: ^5.0.0+2
  carousel_slider: ^4.0.0
  timeline_tile: ^2.0.0
  email_validator: ^2.0.1
  flutter_timeline: ^0.3.0
  flutter_math_fork: ^0.5.0
  sqflite: ^2.0.1
  path: ^1.8.0
  firebase_core: ^1.10.3
  firebase_messaging:
  flutter_local_notifications: ^9.1.4
  skeleton_text: ^3.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it:
  dartz:
  connectivity_plus: ^2.2.1
  logger: ^1.1.0
  connectivity_plus_web: ^1.2.0
  maps_launcher:
  smooth_page_indicator: ^1.0.0+2
  sliding_up_panel: ^2.0.0+1
  grouped_list: ^4.2.0
  fl_chart:
  charts_flutter: ^0.12.0
  video_player: ^2.3.0
  percent_indicator:
  shared_preferences: ^2.0.13
  syncfusion_flutter_pdfviewer: ^20.1.50-beta
  firebase_analytics: ^9.1.9
  flutter_image_compress: ^1.1.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  flutter_secure_storage: ^5.0.2
  flutter_dotenv: ^5.0.2
  hex: ^0.2.0
  image_cropper: ^1.3.0
  modal_bottom_sheet: ^2.0.1
  flutter_staggered_grid_view: ^0.6.2
  dio: ^4.0.6
  restart_app: ^1.1.0
  new_version:
  file_picker: ^4.6.1
  collection: ^1.15.0
  truncate: ^3.0.1
  flutter_svg: ^0.23.0+1
  input_history_text_field: ^0.1.0
  html_unescape: ^2.0.0
  group_radio_button: ^1.2.0
  flutter_custom_dialog: ^1.3.0
  numberpicker: ^2.1.1
  dropdown_button2:
  share_plus: ^4.5.3
  google_fonts: ^4.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner:

dependency_overrides:
  image_picker_android: 0.8.4+13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/garuda/
    - assets/kedaireka/
    - assets/sivil/
    - assets/selancar/
    - assets/selancar/icons/
    - assets/km/
    - assets/km/tableau/
    - assets/km/program-logo/
    - assets/km/icons/
    - assets/pddikti/
    - assets/pddikti/icon/
    - assets/pddikti/homepage/
    - assets/ilustrasiPengumuman/
    - assets/ijazahln/
    - assets/beasiswa/
    - assets/icons/
    - assets/icons/ijazahln/
    - assets/icons/pddikti/
    - assets/icons/tabbar/
    - assets/faq/
    - assets/notifikasi/
    - assets/hubungiKami/
    - assets/carousel/
    - assets/search/
    - assets/default-con/
    - assets/tableau.html
    - assets/splash/
    - assets/certificates/satudikti.crt
    - assets/certificates/satudikti.key
    - assets/profil/
    - assets/siaga/
    - assets/sinta/
    - assets/kompetensiDosen/
    - assets/tracerStudy/
    - assets/sister/
    - assets/gmagz/
    - assets/bima/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: fonts/PlusJakartaSans-Regular.ttf
        - asset: fonts/PlusJakartaSans-Bold.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
